version: '3'
services: 
  postgres:
    image: 'postgres'
    restart: always
    container_name: 'my_postgres_database'
    environment: 
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=my-db
    ports:
      - '5432:5432'
    volumes: 
      - db_data:/var/lib/postgresql/data
  
  pgadmin:
    image: 'dpage/pgadmin4'
    container_name: 'my_pg_admin'
    restart: always
    depends_on: 
      - postgres
    environment: 
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports: 
      - '5050:80'

volumes: 
  db_data: